//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDose.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource_cs_CZ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_cs_CZ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartDose.Helpers.Resources.AppResource.cs-CZ", typeof(AppResource_cs_CZ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Projektu.
        /// </summary>
        internal static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tato aplikace byla vytvořena, aby ulehčila práci zdravotnickému i lékařskému personálu. Je určena pro výpočet úvodní rychlosti infuze při heparinizaci a následné úpravy rychlosti dle aPPTr, případně pro podání bolusové dávky dle aPTTr. Dále slouží jako kalkulačka pro výpočet podání krátkodobého rychle působícího inzulinu u pacientů s nestabilní glykémií. Aplikace funguje plně offline..
        /// </summary>
        internal static string AboutProjectDescription {
            get {
                return ResourceManager.GetString("AboutProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nás.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medička: Iveta Martínková
        ///Matematické vzorce a design: Jan Řehoř
        ///Hlavní programátor: Martin Lahučký.
        /// </summary>
        internal static string AboutUsDescription {
            get {
                return ResourceManager.GetString("AboutUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypočítat.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacharidy v jídle.
        /// </summary>
        internal static string CarbsInMeal {
            get {
                return ResourceManager.GetString("CarbsInMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna rychlosti.
        /// </summary>
        internal static string ChangeOfRate {
            get {
                return ResourceManager.GetString("ChangeOfRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vymazat.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Současná aPTTr.
        /// </summary>
        internal static string CurrentAPTTr {
            get {
                return ResourceManager.GetString("CurrentAPTTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální glykémie.
        /// </summary>
        internal static string CurrentGlucose {
            get {
                return ResourceManager.GetString("CurrentGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rychlost dávkování.
        /// </summary>
        internal static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denní dávka.
        /// </summary>
        internal static string DailyDose {
            get {
                return ResourceManager.GetString("DailyDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dávka:.
        /// </summary>
        internal static string Dose {
            get {
                return ResourceManager.GetString("Dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to První výpočet.
        /// </summary>
        internal static string FirstCalculation {
            get {
                return ResourceManager.GetString("FirstCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inzulín.
        /// </summary>
        internal static string Insulin {
            get {
                return ResourceManager.GetString("Insulin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, zadejte všechny nezbytné hodnoty..
        /// </summary>
        internal static string NumberAlert {
            get {
                return ResourceManager.GetString("NumberAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet jednotek.
        /// </summary>
        internal static string NumberOfUnits {
            get {
                return ResourceManager.GetString("NumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rychlost dávkování:.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to j.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objem.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Cílová aPTTr    .
        /// </summary>
        internal static string WantedAPPTr {
            get {
                return ResourceManager.GetString("WantedAPPTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cílová glykémie.
        /// </summary>
        internal static string WantedGlucose {
            get {
                return ResourceManager.GetString("WantedGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stiskněte znovu zpět pro ukončení aplikace.
        /// </summary>
        internal static string WarningExit {
            get {
                return ResourceManager.GetString("WarningExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váha.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
