//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartDose.Helpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartDose.Helpers.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        internal static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Project.
        /// </summary>
        internal static string AboutProject {
            get {
                return ResourceManager.GetString("AboutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application was created to facilitate the work of medical and medical staff. It is intended for calculation of the initial infusion rate during heparinization and subsequent adjustment of the rate according to aPPTr, or for the administration of a bolus dose according to aPTTr. It also serves as a calculator for calculating the administration of short-acting fast-acting insulin in patients with unstable glycemia. The application works fully offline..
        /// </summary>
        internal static string AboutProjectDescription {
            get {
                return ResourceManager.GetString("AboutProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medic: Iveta Martínková
        ///Mathamtics and design: Jan Řehoř
        ///Chief programmer: Martin Lahučký.
        /// </summary>
        internal static string AboutUsDescription {
            get {
                return ResourceManager.GetString("AboutUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolus:.
        /// </summary>
        internal static string Bolus {
            get {
                return ResourceManager.GetString("Bolus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carbs in meal.
        /// </summary>
        internal static string CarbsInMeal {
            get {
                return ResourceManager.GetString("CarbsInMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of rate.
        /// </summary>
        internal static string ChangeOfRate {
            get {
                return ResourceManager.GetString("ChangeOfRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current aPTTr.
        /// </summary>
        internal static string CurrentAPTTr {
            get {
                return ResourceManager.GetString("CurrentAPTTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current glycemia.
        /// </summary>
        internal static string CurrentGlucose {
            get {
                return ResourceManager.GetString("CurrentGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed.
        /// </summary>
        internal static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily dose.
        /// </summary>
        internal static string DailyDose {
            get {
                return ResourceManager.GetString("DailyDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose:.
        /// </summary>
        internal static string Dose {
            get {
                return ResourceManager.GetString("Dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First calculation.
        /// </summary>
        internal static string FirstCalculation {
            get {
                return ResourceManager.GetString("FirstCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heparin.
        /// </summary>
        internal static string Heparin {
            get {
                return ResourceManager.GetString("Heparin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insulin.
        /// </summary>
        internal static string Insulin {
            get {
                return ResourceManager.GetString("Insulin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all necessary values..
        /// </summary>
        internal static string NumberAlert {
            get {
                return ResourceManager.GetString("NumberAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of units.
        /// </summary>
        internal static string NumberOfUnits {
            get {
                return ResourceManager.GetString("NumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate: .
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartDose.
        /// </summary>
        internal static string SmartDose {
            get {
                return ResourceManager.GetString("SmartDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string UnitCarbsInMeal {
            get {
                return ResourceManager.GetString("UnitCarbsInMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml/h.
        /// </summary>
        internal static string UnitCurrentRate {
            get {
                return ResourceManager.GetString("UnitCurrentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmol/l.
        /// </summary>
        internal static string UnitGlucose {
            get {
                return ResourceManager.GetString("UnitGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        internal static string UnitVolume {
            get {
                return ResourceManager.GetString("UnitVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string UnitWeight {
            get {
                return ResourceManager.GetString("UnitWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted aPPTr.
        /// </summary>
        internal static string WantedAPPTr {
            get {
                return ResourceManager.GetString("WantedAPPTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted glycemia.
        /// </summary>
        internal static string WantedGlucose {
            get {
                return ResourceManager.GetString("WantedGlucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press back again to exit.
        /// </summary>
        internal static string WarningExit {
            get {
                return ResourceManager.GetString("WarningExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
